# Brève introduction à Numpy
`numpy` est un module particulier, qui implémente de nouveaux types de variables: les tableaux multidimensionnels de nomnbres. Ce module implémente également des fonctions compilées qui sont très efficaces lorsqu'elles sont effectuée globalement sur ces tableaux.

## Premier exemple de vectorisation 
On importe le module `numpy` et on le nomme `np` pour simplifier l'écriture ensuite.

In [1]:
import numpy as np

On peut utiliser le module `time` pour mesurer le temps d'exécution du code. Il existe une meilleure solution qui s'appelle `timit`, mais qui d'utilisation plus technique.

In [2]:
import time

Supposons par exemple que l'on veut calculer la somme de $k=0$ à $p$ des sommes $0 \le i < 10^k$ de $10^{-k}$, qui est en théorie égale à $p+1$.

In [4]:
p = 7
t1 = time.clock()
S = 0.0
for k in range(p+1):
    for i in range(10**k):
        S = S + 10.0**(-k)
t2 = time.clock()
print("Somme : {0:13.6e} -- erreur : {1:13.6e} -- durée : {2:13.6e}".
      format(S,p+1-S,t2-t1))

Somme :  8.000000e+00 -- erreur : -2.903771e-09 -- durée :  2.666068e+00


Ci-dessus, l'affichage a été mis en forme avec la fonction `format()` de python (python 3 seulement).

À la place, on peut, par exemple, créer un tableau pour chacune des étapes (boucle $i$ ci dessous), et observer que le calcul est beaucoup plus rapide.

In [5]:
t1 = time.clock()
S = 0.0
for k in range(p+1):
    N = np.ones(10**k) * 10**(-k)
    S = S + np.sum(N)
t2 = time.clock()
print("Somme : {0:13.6e} -- erreur : {1:13.6e} -- durée : {2:13.6e}".
      format(S,p+1-S,t2-t1))

Somme :  8.000000e+00 -- erreur : -1.598721e-14 -- durée :  7.245600e-02


## Exemples de déclaration de tableaux
Et voici quelques exemples de déclaration de tableau.

In [6]:
a = np.array([1,3,2,0,1,-4])
print("a = \n{} est de type {}".format(a,type(a)))

b = np.array([[4.,2.],[1.,3.]])
print("b = \n{} est de type {}".format(b,type(b)))

a = 
[ 1  3  2  0  1 -4] est de type <class 'numpy.ndarray'>
b = 
[[ 4.  2.]
 [ 1.  3.]] est de type <class 'numpy.ndarray'>


Les fonctions ci-dessous permettent d'initialiser des tableaux à des valeurs courantes: $0$, $1$, une suite de nombre. Par ailleurs, ils servent à réserver a priori la mémoire pour un tableau lorsque l'on connait sa taille à l'avance.

In [16]:
print(np.zeros((2,10))) # crée un tableau de float
print(np.ones((3,4)))   # idem 
print(np.arange(5))     # crée un tableau d'int
print(np.arange(5, dtype=float)) # pour forcer un float

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[0 1 2 3 4]
[ 0.  1.  2.  3.  4.]


D'autres fonctions utiles:
- `np.linspace` : maillage régulier d'un intervalle 1D
- `np.eye`, `np.identity` : matrice identité
- `np.meshgrid`, `np.mgrid` : maillages d'un rectangle 2D
- ...

In [12]:
print(np.eye(4,2))
print(np.identity(3))

[[ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Indices et méthodes d'interrogation des tableaux
Les indices commencent à 0, et on peut considérer des parties de tableaux en désignant leurs indices. Il existent de nombreuses possiblités pour cela.

In [13]:
print("a[0] = {} et b[0] = {}".format(a[0],b[0,0]))
print("a[1:3] = {}".format(a[1:3])) # indices 1 et 2
print("b[1,:] = {}".format(b[1,:])) # toute la ligne 1

a[0] = 1 et b[0] = 4.0
a[1:3] = [3 2]
b[1,:] = [ 1.  3.]


Il existent de nombreuses méthodes sur ces tableaux, en voici quelques unes pour connaître la taille ou le type de données du tableau, entre autres.

In [9]:
print(a.shape, a.dtype) # Bien noter que a est déclaré avec des entiers (sans le .)
print(b.shape, b.dtype) # alors que b est déclaré avec des float (avec le . décimal).
print("Is the number 2 in the array a ? {}".format(2 in a))
print("Is the number 2 in the array b ? {}".format(2 in b))

(6,) int64
(2, 2) float64
Is the number 2 in the array a ? True
Is the number 2 in the array b ? True


## Forme, copies
Pour changer la forme d'un tableau, sans changer le nombre total d'éléments, on utilise la fonction `reshape()`.

In [15]:
c = a.reshape((3,2))
print("a vaut {} et a.reshape((2,3)) vaut \n{}".format(a,c))

a vaut [ 1  3  2  0  1 -4] et a.reshape((2,3)) vaut 
[[ 1  3]
 [ 2  0]
 [ 1 -4]]


**Attention**, l'association `=` ne crée pas toujours un nouveau tableau, mais plutôt un nouvel identifiant sur la même zone mémoire.

In [16]:
d = c
c[0,0] = 10
# Mais les deux identifiant pointent vers la même zone mémoire
print("c vaut \n{}".format(c))
print("d vaut \n{}".format(d))

c vaut 
[[10  3]
 [ 2  0]
 [ 1 -4]]
d vaut 
[[10  3]
 [ 2  0]
 [ 1 -4]]


Les deux identifiants pointe vers le même tableau, il s ont donc la même valeur, bien que seul `c[0,0]` est été modifié. Pour créer une copie d'un tableau, il faut utiliser `copy()`.

In [17]:
d = c.copy()
c[0,0] = 100
print("c vaut \n{}".format(c))
print("d vaut \n{}".format(d))

c vaut 
[[100   3]
 [  2   0]
 [  1  -4]]
d vaut 
[[10  3]
 [ 2  0]
 [ 1 -4]]


## Opérations
Les opérations habituelles, $+$, $-$, $*$, $/$ sont distribués sur les éléments des tableaux, de même que les fonctions trigonométriques, puissance, logarithmiques, etc. Pour cela, il faut utiliser les fonction du module `numpy`.

In [19]:
x = np.array([1.,2.,3.])
y = np.array([1.,0.,2.])
M = np.array([[4.,2.,0.],
              [2.,4.,2.],
              [0.,2.,4.]])
print("x = \n{}\ny = \n{}\nM = \n{}".format(x,y,M))
# x+y, x-y, se comportent comme prévu
print(x,y,x+y,x-y)
# x*y et x/y distribuent les opérations sur les tableaux
print(x,y,x*y,y/x,x/y) # Notons que la division par 0 n'est qu'un avertissement. Le calcul peut continuer

x = 
[ 1.  2.  3.]
y = 
[ 1.  0.  2.]
M = 
[[ 4.  2.  0.]
 [ 2.  4.  2.]
 [ 0.  2.  4.]]
[ 1.  2.  3.] [ 1.  0.  2.] [ 2.  2.  5.] [ 0.  2.  1.]
[ 1.  2.  3.] [ 1.  0.  2.] [ 1.  0.  6.] [ 1.          0.          0.66666667] [ 1.   inf  1.5]


/usr/lib64/python3.6/site-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in true_divide
  # Remove the CWD from sys.path while we load stuff.


On peut avoir des surprses parce que numpy repète un tableau pour le mettre à la bonne taille chaque fois que c'est possible. Par exemple `M+x` semble impossible, mais en fait `+` va répeter `x` en face de chaque ligne de `M`.

In [20]:
print(M+x)

[[ 5.  4.  3.]
 [ 3.  6.  5.]
 [ 1.  4.  7.]]


Les fonctions trigonométriques, la fonction racine carrée, etc sont distribuées.

In [22]:
print("sin(x) = {} et sqrt(x) = {}".format(np.sin(x), np.sqrt(x)))

sin(x) = [ 0.84147098  0.90929743  0.14112001] et sqrt(x) = [ 1.          1.41421356  1.73205081]


Les nombres $\pi$ et $\text{e}$ sont donc connus du module `numpy`.

In [24]:
print("pi = {} et e = {}".format(np.pi, np.e))

pi = 3.141592653589793 et e = 2.718281828459045


Il existe aussi des fonctions globales sur les tableaux, et des méthodes pour faire des comparaisons, trouver des indices, etc.

In [27]:
print("La somme des coefficients de M est {} et leur produit est {}".
      format(np.sum(M), np.prod(M)))
print("Rappelons que x = {} et y = {}".format(x,y))
print("x = y ? {} \nx >= y ? {}".format(x==y,x>=y))
print("all(x = y) ? {} \nall(x >= y) ? {}".format(np.all(x==y),np.all(x>=y)))
print("any(x = y) ? {} \nany(x >= y) ? {}".format(np.any(x==y),np.any(x>=y)))

La somme des coefficients de M est 20.0 et leur produit est 0.0
Rappelons que x = [ 1.  2.  3.] et y = [ 1.  0.  2.]
x = y ? [ True False False] 
x >= y ? [ True  True  True]
all(x = y) ? False 
all(x >= y) ? True
any(x = y) ? True 
any(x >= y) ? True


## Algèbre linéaire
Le produit matriciel, au sens mathématique, est réalisé par la fonction `dot()`., Il existe aussi
- `np.outer` : produit extérieur
- `np.inner` : produit scalaire
- `np.cross` : produit vectoriel
Et dans le sous-module `np.linalg`, on trouve les méthodes
- `np.linalg.solve` : résolution d'un système linéaire
- `np.linalg.eig` : valeurs propres et vecteurs propres

In [20]:
y = np.dot(M,x)
print("M*x = {}".format(y))
M_carre = np.dot(M,M)
print("M^2 = \n{}".format(M_carre))

z = np.linalg.solve(M,y)
print("Solution de Mx=y : {}".format(z))
print("Vecteur erreur : {}, \net sa norme : {:}".format(x-z, np.linalg.norm(x-z)))
[D,P] = np.linalg.eig(M)
print("Les valeurs propres de M : {}".format(D))

M*x = [  8.  16.  16.]
M^2 = 
[[ 20.  16.   4.]
 [ 16.  24.  16.]
 [  4.  16.  20.]]
Solution de Mx=y : [ 1.  2.  3.]
Vecteur erreur : [  2.22044605e-16  -4.44089210e-16   4.44089210e-16], 
et sa norme : 6.661338147750939e-16
Les valeurs propres de M : [ 6.82842712  4.          1.17157288]


## Aide
On peut voir ce qui est disponible dans ce sous-module avec l'aide.

In [32]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

L'aide complète de `numpy` est disponible aussi. Elle est plus longue, et ne rentre pas dans ce document. Par contre, on peut voir la documentation de la méthode de résolution des systèmes linéaires.

In [34]:
help(np.linalg.solve)

Help on function solve in module numpy.linalg.linalg:

solve(a, b)
    Solve a linear matrix equation, or system of linear scalar equations.
    
    Computes the "exact" solution, `x`, of the well-determined, i.e., full
    rank, linear matrix equation `ax = b`.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Coefficient matrix.
    b : {(..., M,), (..., M, K)}, array_like
        Ordinate or "dependent variable" values.
    
    Returns
    -------
    x : {(..., M,), (..., M, K)} ndarray
        Solution to the system a x = b.  Returned shape is identical to `b`.
    
    Raises
    ------
    LinAlgError
        If `a` is singular or not square.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The solutions are computed using LAPACK routine _gesv
    
    `a` must be square and of full-rank, i.e., all rows (or, equivalently,
    columns) must be linea